use super::registry::{command_group_name, is_running_safe_command_name, CommandHelpSummary};
use anyhow::{bail, Result};

pub(super) fn help_text() -> String {
    let mut lines = help_topics()
        .iter()
        .map(|topic| topic.listing)
        .collect::<Vec<_>>();
    lines.push("");
    lines.push("Run `/help <command>` for details, or `/help all` for the full guide.");
    lines.join("\n")
}

pub(super) fn help_for(args: &[String]) -> Result<String> {
    match args {
        [] => Ok(help_text()),
        [topic] if topic == "all" => Ok(help_topics()
            .iter()
            .map(format_help_topic)
            .collect::<Vec<_>>()
            .join("\n\n")),
        [topic] => {
            let normalized = normalize_help_topic(topic);
            help_topics()
                .iter()
                .find(|item| item.name == normalized)
                .map(format_help_topic)
                .ok_or_else(|| {
                    anyhow::anyhow!("unknown help topic `{topic}`; run `/help` to list commands")
                })
        }
        _ => bail!("usage: /help [command|all]"),
    }
}

pub(super) fn help_summaries() -> Vec<CommandHelpSummary> {
    help_topics()
        .iter()
        .map(|topic| CommandHelpSummary {
            name: topic.name,
            listing: topic.listing,
            summary: topic.summary,
            usage: topic.usage,
            examples: topic.examples,
            notes: topic.notes,
            running_safe: is_running_safe_command_name(topic.name),
            group: command_group_name(topic.name),
        })
        .collect()
}

pub(super) fn command_names() -> Vec<&'static str> {
    help_topics().iter().map(|topic| topic.name).collect()
}

struct CommandHelp {
    name: &'static str,
    listing: &'static str,
    summary: &'static str,
    usage: &'static [&'static str],
    examples: &'static [&'static str],
    notes: &'static [&'static str],
}

fn help_topics() -> &'static [CommandHelp] {
    &[
        CommandHelp {
            name: "/help",
            listing: "/help [command|all]",
            summary: "List slash commands or show command-specific usage.",
            usage: &["/help", "/help <command>", "/help all"],
            examples: &["/help quickstart", "/help env", "/help /credentials"],
            notes: &["Command names can be provided with or without the leading slash. Use `/quickstart` for a task-oriented first-run guide."],
        },
        CommandHelp {
            name: "/version",
            listing: "/version [--json] [--output path]",
            summary: "Show deepcli version, workspace, config, provider, and command metadata.",
            usage: &[
                "/version",
                "/version --json",
                "/version --output <workspace-relative-path>",
                "/about [--json] [--output path]",
                "deepcli version --json",
            ],
            examples: &[
                "/version",
                "/version --json --output .deepcli/exports/version.json",
                "deepcli version",
                "deepcli about --json",
            ],
            notes: &["`/version` is a local support and acceptance shortcut. It is richer than `deepcli --version`: it includes the current workspace, project config presence, default provider, provider turn timeout, provider count, command count, next diagnostic actions, and a JSON checklist without creating a session or calling a provider. Use `--json` for the stable `deepcli.version.v1` schema, and use `/about` as an alias."],
        },
        CommandHelp {
            name: "/init",
            listing: "/init [--quick|--no-env] [--probe-provider] [--provider <name>]",
            summary: "Bootstrap deepcli project state and show the next setup actions.",
            usage: &[
                "/init",
                "/init --quick",
                "/init --probe-provider",
                "/init --probe-provider --provider <name>",
            ],
            examples: &["/init --quick", "/init --probe-provider --provider deepseek"],
            notes: &["`/init` performs the same low-risk local scaffolding as `/doctor --fix`, then reports provider, permission, test, and environment next actions. Use `--quick` or `--no-env` to skip slower Docker/Colima checks."],
        },
        CommandHelp {
            name: "/status",
            listing: "/status [--json] [--output path]",
            summary: "Show the active session, provider, model, workspace, and plan status.",
            usage: &[
                "/status",
                "/status --json",
                "/status --output <workspace-relative-path>",
            ],
            examples: &[
                "/status",
                "/status --json",
                "/status --json --output .deepcli/exports/status.json",
            ],
            notes: &["`/status` defaults to a compact human-readable report. Use `--json` for the stable `deepcli.status.v1` schema in dashboards, scripts, or external UIs. Use `--output` to write the selected format to a workspace-contained file."],
        },
        CommandHelp {
            name: "/usage",
            listing: "/usage [--json] [--output path] [session_id|--current]",
            summary: "Summarize provider usage and diagnostics for a session.",
            usage: &[
                "/usage",
                "/usage <session_id>",
                "/usage --current",
                "/usage --json",
                "/usage --output <workspace-relative-path>",
            ],
            examples: &[
                "/usage",
                "/usage --current",
                "/usage --json --output .deepcli/exports/usage.json",
            ],
            notes: &["Without an explicit session, empty one-shot sessions fall back to the latest session with activity. Use `--json` for the stable `deepcli.usage.v1` schema when investigating latency, context size, cache hit rate, provider probes, tool failures, or failed tests. Use `--output` to write the selected format to a workspace-contained file."],
        },
        CommandHelp {
            name: "/quickstart",
            listing: "/quickstart [--check] [--json] [--output path] [--fail-on-missing]",
            summary: "Show the shortest path to start, configure, code, resume, and verify with deepcli.",
            usage: &[
                "/quickstart",
                "/quickstart --check",
                "/quickstart --json",
                "/quickstart --output <workspace-relative-path>",
                "/quickstart --json --fail-on-missing",
                "/help quickstart",
                "deepcli quickstart",
            ],
            examples: &[
                "deepcli",
                "deepcli quickstart --check",
                "deepcli quickstart --json --output .deepcli/exports/quickstart.json",
                "deepcli quickstart --json --fail-on-missing",
                "deepcli doctor --quick",
                "deepcli credentials set deepseek",
                "deepcli completion zsh",
                "deepcli deepseek ask '阅读项目结构并说明如何运行测试'",
                "deepcli resume",
                "deepcli accept --json",
                "deepcli gate --json",
            ],
            notes: &[
                "Plain `/quickstart` is authorization-free and only prints this static guide; add `--check`, `--json`, `--output`, or `--fail-on-missing` to inspect the current workspace without creating a session or calling a provider. The check report includes deepcli version, registered slash command count, and provider turn timeout so first-run artifacts are self-contained.",
                "In JSON mode, top-level `nextActions` are directly executable `deepcli ...` commands and `checklist[]` labels that action queue; explanatory onboarding remains in `steps` and `report`.",
                "Use `--fail-on-missing` when CI or an onboarding script should exit non-zero if project config, default provider credentials, or tests are missing.",
                "Start in any project directory with `deepcli`; use `deepcli deepseek` or `deepcli kimi` to pin a provider/model for the TUI.",
                "Use `/model list` and `/model set deepseek deepseek-v4-pro` or `/model set kimi kimi-for-coding` to switch models inside a session.",
                "Use `deepcli completion zsh|bash|fish` to install shell completion when you prefer command-line workflows over the TUI palette.",
                "Use `/env plan compiler --smoke` before `deepcli setup compiler --smoke` when Docker/compiler dependencies may need installation.",
                "Use `/status`, `/usage`, `/trace --limit 20`, `/logs --limit 80`, and `/session tools --failed --limit 5` to debug slow or failed runs.",
                "Use `/accept --env-check compiler --json`, `/gate --env-check compiler --json`, and `/handoff --pr` before handing work back.",
            ],
        },
        CommandHelp {
            name: "/recipes",
            listing: "/recipes [topic|all] [--json] [--output path]",
            summary: "Show task-oriented command recipes for common deepcli workflows.",
            usage: &[
                "/recipes",
                "/recipes start",
                "/recipes code",
                "/recipes debug",
                "/recipes release",
                "/recipes support",
                "/recipes environment",
                "/recipes shell",
                "/recipes sota",
                "/recipes --json",
                "/recipes sota --json --output <workspace-relative-path>",
                "deepcli recipes product-loop --json",
                "deepcli recipes release --json",
                "deepcli playbook support",
            ],
            examples: &[
                "/recipes",
                "/recipes sota",
                "/recipes release",
                "/recipes debug --json",
                "/recipes --json --output .deepcli/exports/recipes.json",
                "deepcli recipes product-loop --json",
                "deepcli recipes release",
                "deepcli playbook support",
            ],
            notes: &["`/recipes` is a local command catalog for task-oriented workflows. It does not create a session or call a provider; use it when `/help all` is too broad and `/quickstart` is too introductory. Supported topics are start, code, debug, release, support, environment, shell, and sota. `product-loop`, `benchmark`, and `round` are aliases for `sota`. Use `--json` for the stable `deepcli.recipes.v1` schema, including top-level `title`, `summary`, and `checklist` fields for UIs that want to render the selected workflow without parsing the text report."],
        },
        CommandHelp {
            name: "/scorecard",
            listing: "/scorecard [--json] [--output path] [--fail-below n]",
            summary: "Measure deepcli product capability coverage against a SOTA-oriented rubric.",
            usage: &[
                "/scorecard",
                "/scorecard --json",
                "/scorecard --output <workspace-relative-path>",
                "/scorecard --fail-below <percent>",
                "/benchmark scorecard [--json] [--output path]",
                "deepcli scorecard --json",
                "deepcli benchmark --fail-below 85",
            ],
            examples: &[
                "/scorecard",
                "/scorecard --json --output .deepcli/exports/scorecard.json",
                "/scorecard --fail-below 85",
                "deepcli benchmark scorecard --json",
                "deepcli deepseek scorecard --json",
            ],
            notes: &["`/scorecard` is a local product readiness report. It scores command coverage, agent workflow, session continuity, verification, safety, provider/model operations, support, and benchmark evidence without creating a session or calling a provider. Use `--json` for the stable `deepcli.scorecard.v1` schema; top-level `checklist[]` labels the global next-action queue while `categories[].checklist[]` labels category-specific actions. When gaps exist, the global `nextActions` list starts with remediation actions, so a report with only benchmark evidence gaps points first to the `/round --json --run-benchmark --fail-on-command` remediation. When there are no gaps, global `nextActions` switch to the sustained product loop: round, preflight, gate, SOTA recipe, benchmark trends/status, baseline inventory, then baseline template or compare. `/sota` is an alias; `/benchmark` keeps scorecard flag compatibility and also records benchmark artifacts."],
        },
        CommandHelp {
            name: "/opportunities",
            listing: "/opportunities [--json] [--priority p] [--effort e] [--output path]",
            summary: "List current non-blocking product opportunities and their executable action checklist.",
            usage: &[
                "/opportunities",
                "/opportunities --json",
                "/opportunities --priority high --json",
                "/opportunities --effort low --json",
                "/opportunities --priority high --effort low --json",
                "/opportunities --output <workspace-relative-path>",
                "/opportunity --json",
                "deepcli opportunities --json",
            ],
            examples: &[
                "/opportunities",
                "/opportunities --json --output .deepcli/exports/opportunities.json",
                "deepcli opportunities --priority high --json",
                "deepcli opportunities --effort low --json",
                "deepcli opportunity --json",
            ],
            notes: &["`/opportunities` is a local read-only product-loop report. It reuses the current `/round` opportunity objects instead of defining a separate source of truth, so UI surfaces can render opportunity cards without opening the full round report. JSON uses the stable `deepcli.opportunities.v1` schema with top-level `filter`, `recommendedOpportunity`, priority and effort counts, `opportunities[]`, executable `nextActions`, and matching `checklist[]`; `--priority high|medium|low|other` and `--effort high|medium|low|other` narrow the report and action queue while retaining total and available counts. When the round is not ready and no non-blocking opportunities are available, next actions fall back to the round remediation queue."],
        },
        CommandHelp {
            name: "/benchmark",
            listing: "/benchmark [presets|run-suite|run|record|status|gate|summary|trends|baseline-template|compare|baselines|list|show|clean|scorecard] [--json] [--output path]",
            summary: "Run, record, assess, summarize, and inspect local benchmark evidence artifacts.",
            usage: &[
                "/benchmark",
                "/benchmark --json",
                "/benchmark scorecard --fail-below <percent>",
                "/benchmark presets [--json]",
                "/benchmark run-suite [--preset <name>] [--fail-on-command] [--json]",
                "/benchmark run --preset <name> [--timeout seconds] [--fail-on-command] [--json]",
                "/benchmark run --command <cmd> [--timeout seconds] [--fail-on-command] [--json]",
                "/benchmark run -- <cmd>",
                "/benchmark record [--json] [--suite name] [--case name] [--command <cmd>] [--notes text]",
                "/benchmark status [--json] [--output path] [--fail-on-not-ready]",
                "/benchmark gate [--json] [--output path]",
                "/benchmark summary [--json] [--limit n]",
                "/benchmark trends [--json] [--limit n]",
                "/benchmark baseline-template [--name name] [--from-current] [--json] [--output path]",
                "/benchmark compare [--baseline path] [--json]",
                "/benchmark baselines [--json] [--limit n]",
                "/benchmark list [--json] [--limit n]",
                "/benchmark show [latest|artifact-name] [--json]",
                "/benchmark clean [--json] [--dry-run|--force] [--keep n] [--older-than-days n] [--all]",
            ],
            examples: &[
                "/benchmark presets --json",
                "/benchmark run-suite --json --fail-on-command",
                "/benchmark run --preset cargo-test --json --fail-on-command",
                "/benchmark run --command 'cargo test' --json --fail-on-command",
                "/benchmark run --timeout 30 -- printf ok",
                "/benchmark status --json",
                "/benchmark gate --json",
                "/benchmark summary --json",
                "/benchmark trends --json",
                "/benchmark baseline-template --output .deepcli/baselines/competitor.json --json",
                "/benchmark baseline-template --from-current --name current-main --output .deepcli/baselines/current-main.json --json",
                "/benchmark compare --baseline .deepcli/baselines/competitor.json --json",
                "/benchmark baselines --json",
                "/benchmark record --json --suite product --case scorecard",
                "/benchmark list --json",
                "/benchmark show latest --json",
                "/benchmark clean --dry-run --keep 20 --json",
                "/benchmark clean --force --keep 20",
                "deepcli benchmark --fail-below 85",
            ],
            notes: &["`/benchmark` is local and does not call a provider. With no subcommand, with scorecard flags, or with `scorecard`, it preserves the old `/scorecard` behavior. `presets` lists curated local benchmark commands without executing them; `run-suite` executes the default meaningful preset set, or a repeated `--preset` subset, and writes a stable `deepcli.benchmark.suite.v1` report plus normal record artifacts; `run --preset <name>` executes one selected preset explicitly. `run` executes an explicitly provided local command with a bounded timeout and writes a stable `deepcli.benchmark.record.v1` artifact under `.deepcli/benchmarks/`; `record` stores declared evidence without executing shell; `status` classifies local evidence as missing, weak, incomplete, failing, stale, or ready with the stable `deepcli.benchmark.status.v1` schema and required preset coverage details; `status --fail-on-not-ready` and `gate` return a non-zero exit when evidence is not ready; `summary` aggregates local history into the stable `deepcli.benchmark.summary.v1` schema; `trends` reports recent per-case status and duration movement with `deepcli.benchmark.trends.v1`, and returns `insufficient_history` when artifacts exist but no case has a previous sample yet; in that state its first next action runs `deepcli round --json --run-benchmark --fail-on-command`, so one command creates a comparable sample and prints the refreshed round report. `baseline-template` emits an editable `deepcli.benchmark.baseline.v1` JSON file with `status=needs_values`, `nextActions`, and `report`, and writes it to a workspace-contained path when `--output` is supplied; stdout-only reports first recommend rerunning with `--output` instead of comparing a file that was not written. Add `--from-current` to prefill required cases from the latest local benchmark artifacts and produce a compare-ready baseline when evidence is complete. `compare` reads local artifacts plus an optional workspace-contained baseline JSON and emits `deepcli.benchmark.compare.v1`; `baselines` lists local baseline files, readiness, default competitor state, and compare/template actions with `deepcli.benchmark.baselines.v1`; every benchmark JSON report that exposes executable `nextActions` also includes a matching top-level `checklist[]`, while manual edit guidance remains in `nextActions` and `report`; `list` and `show` inspect artifacts; `clean` previews or deletes old local artifacts with `deepcli.benchmark.cleanup.v1`, defaulting to dry-run and keeping the newest 20 artifacts unless `--force` is supplied. While an agent task is running in the TUI, read-only benchmark reports such as `status`, `summary`, `trends`, `compare`, `baselines`, `list`, `show`, `presets`, and scorecard compatibility are allowed; benchmark-producing `run`, `run-suite`, `record`, `baseline-template`, and cleanup actions should wait until the task is stopped or finished."],
        },
        CommandHelp {
            name: "/round",
            listing: "/round [--json] [--output path] [--run-benchmark] [--preset <name>] [--fail-on-command] [--fail-on-gaps] [--fail-below n]",
            summary: "Summarize the current product iteration state, evidence gaps, and next engineering actions.",
            usage: &[
                "/round",
                "/round --json",
                "/round --json --run-benchmark --fail-on-command",
                "/round --json --run-suite --preset cargo-test",
                "/round --output <workspace-relative-path>",
                "/round --fail-on-gaps",
                "/round --fail-below <percent>",
                "deepcli round --json",
                "deepcli round --json --run-benchmark --fail-on-command",
            ],
            examples: &[
                "/round",
                "/round --json --output .deepcli/exports/round.json",
                "/round --json --run-benchmark --fail-on-command",
                "/round --json --fail-on-gaps",
                "deepcli round --json",
            ],
            notes: &["`/round` is a local product-loop report for the designer -> engineer -> verifier cycle. By default it aggregates `/scorecard`, `/benchmark status`, and optional goal readiness into the stable `deepcli.round.v1` schema without creating a session, calling a provider, or executing shell. The `scorecard` gate tracks the round score threshold; benchmark evidence and goal readiness have their own gates, while remaining gaps still keep the round from being ready. The benchmark gate summarizes missing, weak, stale, failed, or timed-out required presets so users can see the evidence gap without opening a second report. The JSON report includes top-level `checklist[]` for the global next-action queue, and each gate includes `nextAction` plus a gate-level `checklist[]`, so UIs can render round-level and gate-level action buttons without parsing the report. The top-level `nextActions` list is ordered by failing gate remediation; when scorecard passes and only benchmark-owned gaps remain, it skips the redundant `deepcli scorecard --json` action and starts with `deepcli round --json --run-benchmark --fail-on-command`. When all gates pass and the round is ready, `nextActions` keeps preflight/gate and then selects the current baseline step: generate `.deepcli/baselines/competitor.json` if it is missing, or run baseline compare when it exists. When a goal exists, the JSON report includes `goalStatus`; an unready goal adds a `goal_readiness` gate and a `deepcli goal gate --json` next action. Add `--run-benchmark` or `--run-suite` when you want one command to execute the benchmark suite first, then report the updated round status. Use `--fail-on-command` to fail when an executed benchmark command fails, and `--fail-on-gaps` or `--strict` when CI should fail unless scorecard, benchmark evidence, and goal readiness are all ready. While an agent task is running in the TUI, read-only `/round` reports are allowed; benchmark-producing `--run-benchmark`, `--run-suite`, `--preset`, `--presets`, `--fail-on-command`, and `--fail-fast` options should wait until the task is stopped or finished."],
        },
        CommandHelp {
            name: "/selftest",
            listing: "/selftest [--json] [--output path] [--fail-on-issues]",
            summary: "Run a local product self-test for install readiness, command wiring, config, Git identity, credentials, sessions, logs, and tests.",
            usage: &[
                "/selftest",
                "/selftest --json",
                "/selftest --output <workspace-relative-path>",
                "/selftest --json --fail-on-issues",
                "deepcli selftest --json",
            ],
            examples: &[
                "/selftest",
                "/selftest --json --output .deepcli/exports/selftest.json",
                "deepcli selftest --json --fail-on-issues",
            ],
            notes: &["`/selftest` is a local acceptance shortcut for the deepcli product itself. It does not create a session or call a provider; it checks the command registry, project config, configured Git identity, default provider credentials, resumable sessions, local logs, test discovery, and support entrypoints. Use `--json` for the stable `deepcli.selftest.v1` schema; JSON `nextActions` are directly executable `deepcli ...`, `cargo ...`, or `git ...` commands, and `checklist[]` labels that action queue for UIs and scripts. Use `--fail-on-issues` in install scripts or CI when missing setup should fail fast."],
        },
        CommandHelp {
            name: "/preflight",
            listing: "/preflight [--json] [--output path] [--dry-run] [--quick] [--fail-fast]",
            summary: "Run a publish-ready local preflight across formatting, tests, diagnostics, privacy, and gate checks.",
            usage: &[
                "/preflight",
                "/preflight --json",
                "/preflight --output <workspace-relative-path>",
                "/preflight --dry-run",
                "/preflight --quick",
                "/preflight --fail-fast",
                "deepcli preflight --json",
                "deepcli release-check --json",
            ],
            examples: &[
                "/preflight --dry-run",
                "/preflight --json --output .deepcli/exports/preflight.json",
                "deepcli preflight --json",
                "deepcli release-check --dry-run",
                "deepcli preflight --quick --json",
            ],
            notes: &["`/preflight` keeps release checks local and does not create a session or call a provider. Full mode keeps going across checks and exits non-zero if any required check fails while preserving the report; `--quick` skips slower clippy/gate checks, and `--dry-run` only lists the commands that would run. JSON reports include a top-level `checklist[]` with step, label, command, status, and required fields for UIs that render the release-check queue without parsing `checks[]` or report text. Text and JSON reports include diagnostics for total measured duration, slowest check, largest output check, and failed required checks. Use `--json` for the stable `deepcli.preflight.v1` schema. While an agent task is running in the TUI, use `/preflight --dry-run --json` for a non-executing plan; full preflight should wait until the task is stopped or finished."],
        },
        CommandHelp {
            name: "/completion",
            listing: "/completion [bash|zsh|fish|json|install|status] [--force] [--json] [--output path]",
            summary: "Generate, install, or inspect shell completion scripts, or export a machine-readable command catalog.",
            usage: &[
                "/completion",
                "/completion zsh",
                "/completion bash",
                "/completion fish",
                "/completion json",
                "/completion install [bash|zsh|fish] [--force] [--json]",
                "/completion status [bash|zsh|fish] [--json]",
                "/completion zsh --output <workspace-relative-path>",
                "deepcli completion zsh",
            ],
            examples: &[
                "deepcli completion status zsh",
                "deepcli completion status zsh --json",
                "deepcli completion install zsh",
                "deepcli completion install zsh --force",
                "deepcli completion install fish --force --json",
                "deepcli completion zsh > ~/.zsh/completions/_deepcli",
                "deepcli completion bash > ~/.local/share/bash-completion/completions/deepcli",
                "deepcli completion fish > ~/.config/fish/completions/deepcli.fish",
                "deepcli completion json --output .deepcli/exports/commands.json",
            ],
            notes: &["`/completion` is local and does not create a session or call a provider. Use `json` for the stable `deepcli.completion.v1` command catalog in external UIs, installers, docs generators, or shell integration tests. `install` defaults to dry-run and only writes the shell completion file under your home directory when `--force` is provided; `--json` on install emits `deepcli.completion.install.v1`. `status` compares the installed script against the current generated script and emits `deepcli.completion.status.v1` with missing/stale/up_to_date state when `--json` is used. `--output` writes the selected script, catalog, install report, or status report to a workspace-contained file."],
        },
        CommandHelp {
            name: "/diagnose",
            listing: "/diagnose [--quick|--full-env] [--probe-provider] [--provider <name>] [--limit n] [--json] [--output path] [--bundle dir] [session_id|--current]",
            summary: "Run a fast workspace health check and include session diagnostics when available.",
            usage: &[
                "/diagnose",
                "/diagnose [docker|compiler] [--json] [--output path]",
                "/diagnose --full-env",
                "/diagnose --probe-provider --provider <name>",
                "/diagnose --limit <n> [session_id|--current]",
                "/diagnose --json",
                "/diagnose --output <workspace-relative-path>",
                "/diagnose --bundle <workspace-relative-dir>",
            ],
            examples: &[
                "/diagnose",
                "/diagnose docker --json",
                "/diagnose --limit 5",
                "/diagnose --full-env",
                "/diagnose --json --output .deepcli/exports/diagnose.json",
                "/diagnose --bundle .deepcli/support/latest",
            ],
            notes: &["`/diagnose` is designed for first-aid checks and defaults to quick mode so it does not block on Docker or environment setup. `/diagnose docker` and `/diagnose compiler` are shortcuts for `/env check <target>` when the user is diagnosing a local task environment. Use `/session diagnose` when you only want a persisted session report. Use `--json` for automation; JSON nextActions are directly executable `deepcli ...` commands and top-level checklist items mirror the executable actions, while explanatory slash quick links stay in the text report. Use `--output` to write the selected format to a workspace-contained file, and `--bundle` to write a redacted support bundle with an issue template plus version, diagnose, quickstart, status, usage, trace, logs, and session-list artifacts."],
        },
        CommandHelp {
            name: "/support",
            listing: "/support [bundle-dir] [diagnose options]",
            summary: "Create a redacted support bundle and issue template without remembering diagnose flags.",
            usage: &[
                "/support",
                "/support <workspace-relative-dir>",
                "/support --json",
                "/support --full-env",
                "/support --probe-provider --provider <name>",
                "deepcli support",
                "deepcli support .deepcli/support/latest",
            ],
            examples: &[
                "/support",
                "/support .deepcli/support/latest",
                "/support --json",
                "deepcli support",
                "deepcli support .deepcli/support/slow-run",
            ],
            notes: &["`/support` is a shortcut for `/diagnose --bundle`; by default it writes `.deepcli/support/latest` and includes `issue.md`, `manifest.json`, `version.json`, `logs.json`, and redacted diagnostic JSON artifacts. JSON nextActions are directly executable `deepcli ...` commands, and top-level checklist items mirror those actions so support UIs and scripts do not need to parse report quick links; the bundle manifest exposes the same checklist contract. The first non-option argument is treated as the bundle directory; use `/diagnose --bundle <dir> <session_id>` when you need an explicit positional session id. Add `--full-env` only when Docker/compiler readiness matters, and `--probe-provider` only when an online provider check is needed."],
        },
        CommandHelp {
            name: "/doctor",
            listing: "/doctor [shell] [--fix] [--quick|--no-env] [--probe-provider] [--provider <name>] [--json] [--output path]",
            summary: "Diagnose configuration, Git identity, credentials, provider readiness, tests, permissions, and local environment.",
            usage: &[
                "/doctor",
                "/doctor shell [--json] [--output path]",
                "/doctor [docker|compiler] [--json] [--output path]",
                "/doctor --quick",
                "/doctor --fix",
                "/doctor --probe-provider",
                "/doctor --probe-provider --provider <name>",
                "/doctor --json",
                "/doctor --output <workspace-relative-path>",
            ],
            examples: &["/doctor --quick", "/doctor shell --json", "/doctor docker --json", "/doctor --quick --json --output .deepcli/exports/doctor.json", "/doctor --fix --quick", "/doctor --probe-provider --provider deepseek"],
            notes: &["Provider probes are online checks and only run when explicitly requested. `/doctor shell` is a local install health check for PATH, whether the `deepcli` command resolves to this workspace, legacy command residue, and shell completion state; it implies `--quick` so it does not run slower Docker/Colima checks. `/doctor docker` and `/doctor compiler` are shortcuts for `/env check <target>` when the user is diagnosing a local task environment. Use `--quick` or `--no-env` to skip slower Docker/Colima checks. The report includes deepcli version, registered command count, default provider, provider turn timeout, and configured Git identity for issue triage. Use `--json` for the stable `deepcli.doctor.v1` schema; JSON top-level `nextActions` are executable shell commands and top-level checklist items mirror the executable actions, while explanatory context remains in `report`, `environment`, and `shell`. Use `--output` to write the selected format to a workspace-contained file."],
        },
        CommandHelp {
            name: "/trace",
            listing: "/trace [--limit n] [--json] [--output path] [session_id|--current]",
            summary: "Show session audit events for provider latency, tool calls, approvals, tests, and model switches.",
            usage: &[
                "/trace",
                "/trace --limit <n>",
                "/trace --limit <n> <session_id>",
                "/trace --current",
                "/trace --json",
                "/trace --output <workspace-relative-path>",
            ],
            examples: &[
                "/trace --limit 20",
                "/trace --json --output .deepcli/exports/trace.json",
            ],
            notes: &["Without an explicit session, empty one-shot sessions fall back to the latest session with audit events. Use `--json` for the stable `deepcli.trace.v1` schema when exporting provider turns, tool calls, approvals, tests, and model switches. JSON payload values are redacted before output. Use `--output` to write the selected format to a workspace-contained file."],
        },
        CommandHelp {
            name: "/logs",
            listing: "/logs [--list|--file name] [--limit n] [--json] [--output path]",
            summary: "Inspect redacted local deepcli log files without creating a session.",
            usage: &[
                "/logs",
                "/logs --list",
                "/logs --file <log-file>",
                "/logs --limit <n>",
                "/logs --json",
                "/logs --output <workspace-relative-path>",
            ],
            examples: &[
                "/logs --limit 80",
                "/logs --list --json",
                "/logs --json --output .deepcli/exports/logs.json",
                "deepcli logs --limit 120",
            ],
            notes: &["`/logs` reads only `.deepcli/logs` in the current workspace, redacts sensitive-looking content, and never creates a session or calls a provider. By default it tails the latest modified log file; use `--list` to inspect available files and `--file <name>` to select one. Use `--json` for the stable `deepcli.logs.v1` schema."],
        },
        CommandHelp {
            name: "/privacy",
            listing: "/privacy [scan] [--json] [--output path] [--fail-on-findings] [--limit n] [--no-history]",
            summary: "Scan git history and tracked paths for likely secrets or privacy metadata before sharing a repo.",
            usage: &[
                "/privacy",
                "/privacy scan",
                "/privacy --json",
                "/privacy --output <workspace-relative-path>",
                "/privacy --fail-on-findings",
                "/privacy --limit <revision-count>",
                "/privacy --no-history",
                "deepcli privacy --json",
            ],
            examples: &[
                "/privacy",
                "/privacy --json --output .deepcli/exports/privacy.json",
                "/privacy --fail-on-findings",
                "deepcli privacy --json",
            ],
            notes: &["`/privacy` is local and does not create a session or call a provider. It checks commit author emails, remote URLs, tracked sensitive file paths, historical sensitive file paths, absolute local user-home paths, configured blocked terms, and high-confidence token/private-key patterns. Configure `privacy.allowedEmails` or `privacy.allowedEmailDomains` for public/approved email metadata and content that should be suppressed rather than reported; `privacy.allowedCommitEmails` and `privacy.allowedCommitDomains` apply only to commit metadata. Configure `privacy.blockedTerms` for project-specific terms that must not appear before sharing, and `privacy.allowedTerms` for accepted migration fixtures that should be suppressed. Configure `privacy.allowedUserPaths` with redacted local user-home paths when known historical project roots should be suppressed. Samples are redacted before display. Use `--json` for the stable `deepcli.privacy.scan.v1` schema, and `--fail-on-findings` when an export or release script should stop on high or medium risk findings."],
        },
        CommandHelp {
            name: "/context",
            listing: "/context",
            summary: "Preview workspace context sources that deepcli will consider.",
            usage: &["/context"],
            examples: &["/context"],
            notes: &[],
        },
        CommandHelp {
            name: "/permissions",
            listing: "/permissions [show] [--json] [--output path]|set-mode <sandbox|read|write>",
            summary: "View or adjust the current workspace permission mode.",
            usage: &[
                "/permissions [show] [--json] [--output path]",
                "/permissions set-mode <sandbox|read|write>",
            ],
            examples: &[
                "/permissions",
                "/permissions show --json --output .deepcli/exports/permissions.json",
                "/permissions set-mode sandbox",
            ],
            notes: &["Dangerous shell, package install, Docker setup, and destructive Git commands still require explicit approval. Use `--json` for the stable `deepcli.permissions.show.v1` schema and `--output` to write the selected format to a workspace-contained file."],
        },
        CommandHelp {
            name: "/credentials",
            listing: "/credentials status [provider] [--json] [--output path]|set <provider> [--stdin] [--force]|remove [provider]",
            summary: "Inspect, store, or remove provider API keys.",
            usage: &[
                "/credentials status [provider] [--json] [--output path]",
                "/credentials set <provider> [--stdin] [--force]",
                "/credentials remove [provider]",
            ],
            examples: &[
                "/credentials status",
                "/credentials status deepseek --json --output .deepcli/exports/credentials.json",
                "/credentials set deepseek",
                "/credentials remove deepseek",
                "printf '%s' \"$DEEPSEEK_API_KEY\" | /credentials set deepseek --stdin --force",
            ],
            notes: &["Plaintext API keys are redacted from command output, logs, trace, and session records. `/credentials remove` clears the local file apiKey while preserving provider metadata; if the provider environment variable is still set, it remains active and is reported in the output. Use `--json` for the stable `deepcli.credentials.status.v1` schema and `--output` to write the selected format to a workspace-contained file."],
        },
        CommandHelp {
            name: "/login",
            listing: "/login [provider] [--stdin] [--force]",
            summary: "Shortcut for securely setting a provider API key.",
            usage: &[
                "/login [provider] [--stdin] [--force]",
                "/auth [provider] [--stdin] [--force]",
                "/apikey [provider] [--stdin] [--force]",
                "/key [provider] [--stdin] [--force]",
                "/credentials set [provider] [--stdin] [--force]",
            ],
            examples: &[
                "/login deepseek",
                "printf '%s' \"$DEEPSEEK_API_KEY\" | deepcli login deepseek --stdin --force",
                "deepcli auth kimi",
            ],
            notes: &["`/login`, `/auth`, `/apikey`, and `/key` all map to `/credentials set`. If provider is omitted, deepcli uses the active provider override when available, otherwise the default provider from config. This is local credential setup and should not create a session or call a provider."],
        },
        CommandHelp {
            name: "/logout",
            listing: "/logout [provider]",
            summary: "Shortcut for removing a local provider API key.",
            usage: &["/logout [provider]", "/credentials remove [provider]"],
            examples: &["/logout deepseek", "deepcli logout kimi"],
            notes: &["Alias for `/credentials remove`; clears the apiKey in the local credentials file, preserves endpoint/model metadata, and does not create a session or call a provider."],
        },
        CommandHelp {
            name: "/apikey",
            listing: "/apikey [provider] [--stdin] [--force]",
            summary: "Alias for /login when the user thinks in terms of API keys.",
            usage: &["/apikey [provider] [--stdin] [--force]", "/credentials set [provider] [--stdin] [--force]"],
            examples: &["/apikey deepseek --stdin", "deepcli apikey kimi"],
            notes: &["Alias for `/login`; no provider call is made before the key is stored."],
        },
        CommandHelp {
            name: "/config",
            listing: "/config [show|sources|validate|get <path>] [--json] [--output path]|set <path> <json-value>",
            summary: "Inspect and safely edit effective project configuration.",
            usage: &[
                "/config show [--json] [--output path]",
                "/config sources [--json] [--output path]",
                "/config validate [--json] [--output path]",
                "/config get <path> [--json] [--output path]",
                "/config set <path> <json-value>",
            ],
            examples: &[
                "/config get agent.providerTurnTimeoutSeconds",
                "/config get agent.providerTurnTimeoutSeconds --json --output .deepcli/exports/config-timeout.json",
                "/config sources --json --output .deepcli/exports/config-sources.json",
                "/config set agent.providerTurnTimeoutSeconds 900",
            ],
            notes: &["Set values must be valid JSON scalars or objects, depending on the target path. Use `--json` for the stable `deepcli.config.inspect.v1` schema on read-only config commands and `--output` to write the selected format to a workspace-contained file."],
        },
        CommandHelp {
            name: "/timeout",
            listing: "/timeout [show|set <seconds>|reset] [--json] [--output path]",
            summary: "Show or update provider turn timeout without remembering the config path.",
            usage: &[
                "/timeout [show|set <seconds>|reset] [--json] [--output path]",
                "/timeout",
                "/timeout --json",
                "/timeout <seconds>",
                "/timeout set <seconds>",
                "/timeout reset",
                "/config get agent.providerTurnTimeoutSeconds",
            ],
            examples: &[
                "/timeout",
                "/timeout 900",
                "/timeout reset",
                "deepcli timeout --json --output .deepcli/exports/timeout.json",
            ],
            notes: &["`/timeout` is a local shortcut for `agent.providerTurnTimeoutSeconds`. It helps diagnose slow provider turns without changing models or calling a provider. Setting or resetting writes `.deepcli/config.json` and should not create an empty session."],
        },
        CommandHelp {
            name: "/model",
            listing: "/model [show|list] [--json] [--output path]|set <provider> [model]|<provider> [model]",
            summary: "Show, list, or switch the active provider/model for the session.",
            usage: &[
                "/model show [--json] [--output path]",
                "/model list [--json] [--output path]",
                "/model set <provider> [model]",
                "/model <provider> [model]",
            ],
            examples: &[
                "/model show --json --output .deepcli/exports/model.json",
                "/model list --json",
                "/model set deepseek deepseek-v4-pro",
                "/model kimi",
                "/model set kimi kimi-for-coding",
            ],
            notes: &["Model switches update the active session when there is one, and always update the project config. As one-shot commands, `/model set` and `/model <provider>` run locally without creating an empty session or calling a provider. Use `--json` for the stable `deepcli.model.inspect.v1` schema on read-only model commands; the JSON includes executable `nextActions` plus a matching `checklist[]` for model/settings UIs. Use `--output` to write the selected format to a workspace-contained file."],
        },
        CommandHelp {
            name: "/goal",
            listing: "/goal [objective...] [--json] [--output path] [--acceptance-cmd cmd]",
            summary: "Create or inspect a strict session goal contract with stop conditions and acceptance commands.",
            usage: &[
                "/goal",
                "/goal <objective>",
                "/goal start <objective>",
                "/goal status [--json]",
                "/goal gate [--json]",
                "/goal show [--json]",
                "/goal --acceptance-cmd 'cargo test' --acceptance-cmd './scripts/deepcli preflight --json'",
            ],
            examples: &[
                "/goal 完整实现当前项目文档中的全部需求",
                "/goal status --json",
                "/goal gate --json",
                "/goal --json --output .deepcli/exports/goal.json",
                "deepcli goal start 'complete docs/ai requirements'",
            ],
            notes: &["With no existing goal, `/goal` creates a default project-document goal for the active session. The active goal is injected into future agent context and tells the agent not to stop until requirements, acceptance commands, tests, and final verification all pass. Use `/goal status` for the stable `deepcli.goal.status.v1` readiness report, and `/goal gate` when a script should exit non-zero until the goal is ready to complete. `/goal show/status/gate` fall back to the latest session with a goal when no active goal is selected; create, start, and clear still require an active session."],
        },
        CommandHelp {
            name: "/plan",
            listing: "/plan [requirement...] [--json] [--output path] [--write-doc path]",
            summary: "Turn an immature request into clarification questions and a requirements draft.",
            usage: &[
                "/plan",
                "/plan show",
                "/plan <rough requirement>",
                "/plan <rough requirement> --write-doc docs/ai/REQUIREMENTS_DRAFT.md",
                "/plan <rough requirement> --json --output .deepcli/exports/plan.json",
            ],
            examples: &[
                "/plan 做一个更好的会话恢复能力",
                "/plan 支持团队共享配置 --write-doc docs/ai/REQUIREMENTS_DRAFT.md",
                "deepcli plan '支持插件市场'",
            ],
            notes: &["`/plan show` preserves the old behavior and prints the saved execution plan. Passing a requirement creates a product-planning artifact: clarifying questions with 2-3 options and recommended choices, assumptions, functional requirements, acceptance criteria, and next steps. In an active session the questions are also queued as by-the-way questions so the user can answer them interactively. Use `--json` for the stable `deepcli.plan.requirements_draft.v1` schema."],
        },
        CommandHelp {
            name: "/fork",
            listing: "/fork [session_id|--current] [--dry-run|--no-open] [--verify] [--app name] [--json] [--output path]",
            summary: "Clone a saved conversation context and optionally open a new terminal resumed into the clone.",
            usage: &[
                "/fork",
                "/fork --current",
                "/fork <session_id>",
                "/fork --current --dry-run --json",
                "/fork --current --app iTerm2 --dry-run --json",
                "/fork --current --no-open --verify --json",
                "/fork --current --no-open",
                "/fork <session_id> --json --output .deepcli/exports/fork.json",
            ],
            examples: &[
                "/fork --current",
                "/fork --current --dry-run --json",
                "/fork --current --app iTerm2 --dry-run --json",
                "/fork --current --no-open --verify --json",
                "/fork 6155c14e --no-open",
                "deepcli fork 6155c14e --app iTerm2 --no-open --json",
            ],
            notes: &["`/fork` copies the persisted session directory, gives the clone a new id/title, and runs `deepcli resume <new_id>` in a new macOS Terminal by default. If `DEEPCLI_TERMINAL_APP` is unset, deepcli infers supported defaults from `TERM_PROGRAM`, so iTerm users get iTerm2 automatically; set `DEEPCLI_TERMINAL_APP=iTerm2` to make that terminal app explicit for fork and terminal commands, or use `--app iTerm2` / `--terminal-app iTerm2` as a one-shot override. Explicit flags win over the environment, and `DEEPCLI_TERMINAL_APP` wins over `TERM_PROGRAM`. Automatic resume is implemented for Terminal and iTerm2, while other apps should use `--no-open` plus the workspace resume command. In the TUI, `/fork` or `/fork --current` uses the active session; in a shell, `deepcli fork` without an id chooses the latest resumable conversation in the current workspace and skips empty or diagnostic-only sessions. Use `--dry-run` or `--preview` to inspect the selected source, copy mode, planned title, terminal app, and next actions without creating a session. Use `--verify` to add a resume health check to the report, including workspace/provider/model matches and copied message/tool/test/diff/backup counts. Use `--no-open` when you want to create the fork but skip Terminal launch. The JSON report includes `contextCopy`, `terminal.app`, `terminal.autoResumeSupported`, `terminal.workspaceResumeCommand`, optional `verification`, executable `nextActions`, and matching `checklist[]` so UIs can explain whether the source was idle or running and provide named copy-paste actions that work from any shell directory; expected source-selection failures also return `deepcli.session.fork.v1` with `status=error`, `error.code`, next actions, and checklist before exiting non-zero. When shell users pass TUI-only `--current` without an active session, next actions start with `deepcli fork --dry-run --json`; other no-source next actions reuse resume-candidate recovery hints, so hidden empty sessions surface `deepcli session prune-empty --dry-run --json`, diagnostic-only sessions surface `deepcli session diagnose --limit 5 --json`, and candidate discovery remains available through `deepcli resume candidates --json`. When the source is running, the fork is still allowed but only copies persisted files; the in-memory agent task is not hot-forked."],
        },
        CommandHelp {
            name: "/diff",
            listing: "/diff [--staged] [--path path] [--stat|--name-only] [--limit n]",
            summary: "Show workspace diff, with session diff fallback for normal unstaged diff.",
            usage: &[
                "/diff",
                "/diff --staged",
                "/diff --stat",
                "/diff --name-only",
                "/diff --limit <n>",
                "/diff --path <workspace-relative-path>",
            ],
            examples: &[
                "/diff --stat",
                "/diff --name-only --path src",
                "/diff --path src/commands.rs --limit 200",
                "/diff --staged --stat",
            ],
            notes: &["`/diff` prefers Git diff; when Git diff is unavailable or empty, it shows session-recorded diff history if available. `/diff --staged` keeps Git staged-diff semantics. Repeat `--path` to scope output to one or more workspace-relative path prefixes. Use `--stat` or `--name-only` before opening a very large diff; `--limit` caps displayed lines or entries."],
        },
        CommandHelp {
            name: "/review",
            listing: "/review [--path path]",
            summary: "Run a local change review focused on diffs, risks, and sensitive additions.",
            usage: &["/review", "/review --path <workspace-relative-path>"],
            examples: &["/review", "/review --path src/commands.rs"],
            notes: &["Git diff is preferred; when it is unavailable or empty, deepcli reviews session-recorded diff history if available. Repeat `--path` to scope review to one or more workspace-relative path prefixes."],
        },
        CommandHelp {
            name: "/accept",
            listing: "/accept [verify options]",
            summary: "Shortcut for a human acceptance report that runs tests through /verify.",
            usage: &[
                "/accept",
                "/accept --json",
                "/accept --output <workspace-relative-path>",
                "/accept --path <workspace-relative-path>",
                "/accept --test-command '<command>'",
                "/accept --env-check [docker|compiler]",
                "/verify --run-tests [verify options]",
            ],
            examples: &[
                "/accept",
                "/accept --json --output .deepcli/exports/acceptance.json",
                "/accept --path src --test-command 'cargo test'",
                "deepcli accept --json",
            ],
            notes: &["`/accept` maps to `/verify --run-tests` unless an explicit `--test-command` or `-- <command>` is provided. With no current or explicit session it uses workspace-only fresh test evidence instead of falling back to stale session records. It reuses the stable `deepcli.verify.v1` JSON schema and all `/verify` blockers; use `/gate` when the command should exit non-zero on blockers."],
        },
        CommandHelp {
            name: "/gate",
            listing: "/gate [verify options]",
            summary: "Shortcut for a strict acceptance gate that fails when /verify reports blockers.",
            usage: &[
                "/gate",
                "/gate --json",
                "/gate --output <workspace-relative-path>",
                "/gate --path <workspace-relative-path>",
                "/gate --test-command '<command>'",
                "/gate --env-check [docker|compiler]",
                "/verify --run-tests --fail-on-blockers [verify options]",
            ],
            examples: &[
                "/gate",
                "/gate --json --output .deepcli/exports/gate.json",
                "/gate --path src --test-command 'cargo test'",
                "deepcli gate --json",
            ],
            notes: &["`/gate` maps to `/verify --run-tests --fail-on-blockers` unless an explicit test command is provided. With no current or explicit session it uses workspace-only fresh test evidence instead of falling back to stale session records. It is intended for CI, release checks, and final handoff scripts that need a non-zero exit when acceptance blockers remain. JSON output includes `checklist[]` labels for the executable verification next actions."],
        },
        CommandHelp {
            name: "/verify",
            listing: "/verify [--run-tests|--test-command <command>] [--env-check [docker|compiler]] [--path path] [--limit n] [--json] [--output path] [--fail-on-blockers] [session_id|--current]",
            summary: "Assemble an acceptance report from git status, diffs, review findings, tests, and session blockers.",
            usage: &[
                "/verify",
                "/verify --limit <n>",
                "/verify --path <workspace-relative-path>",
                "/verify --run-tests",
                "/verify --test-command 'cargo test'",
                "/verify --env-check [docker|compiler]",
                "/verify --json",
                "/verify --output <workspace-relative-path>",
                "/verify --fail-on-blockers",
                "/verify <session_id>",
                "/verify --current",
            ],
            examples: &["/verify", "/verify --path src/commands.rs --test-command 'cargo test'", "/verify --run-tests", "/verify --test-command 'cargo test'", "/verify --env-check docker --json --output .deepcli/exports/verify.json --fail-on-blockers", "/verify --current"],
            notes: &["`/verify` does not claim acceptance automatically. It highlights missing or weak tests, failed tools, pending approvals, open by-the-way questions, optional environment readiness, and the next commands needed before handoff. Repeat `--path` to scope diff review to one or more workspace-relative path prefixes. Without a current or explicit session, a requested test run uses workspace-only fresh evidence instead of falling back to stale session records. Use `--env-check docker` or `--env-check compiler` to include read-only Docker/compiler environment evidence as a blocker when not ready. Use `--json` for machine-readable status, blockers, environment evidence, next actions, and a top-level `checklist[]` that labels those actions for UIs. Use `--output` to also write the selected output format to a workspace-contained file. Use `--fail-on-blockers` when a script or CI job should exit non-zero if blockers remain."],
        },
        CommandHelp {
            name: "/handoff",
            listing: "/handoff [--path path] [--limit n] [--env-check [docker|compiler]] [--format text|markdown|json|pr] [--output path] [--fail-on-blockers] [session_id|--current]",
            summary: "Create a concise handoff report from workspace diff, review risk, tests, and session signals.",
            usage: &[
                "/handoff",
                "/handoff --path <workspace-relative-path>",
                "/handoff --limit <n>",
                "/handoff --env-check [docker|compiler]",
                "/handoff --markdown",
                "/handoff --pr",
                "/handoff --json",
                "/handoff --fail-on-blockers",
                "/handoff --format <text|markdown|json|pr>",
                "/handoff --output <workspace-relative-path>",
                "/handoff <session_id>",
                "/handoff --current",
            ],
            examples: &[
                "/handoff",
                "/handoff --path src/commands.rs",
                "/handoff --markdown",
                "/handoff --pr",
                "/handoff --pr --output .deepcli/exports/pr-description.md",
                "/handoff --env-check docker --json",
                "/handoff --json",
                "/handoff --json --fail-on-blockers",
                "/handoff --limit 10 --current",
            ],
            notes: &["`/handoff` is read-only unless `--output` is provided. It is intended for final user/PR summaries and highlights missing or weak evidence instead of claiming acceptance automatically. Use `--env-check docker` or `--env-check compiler` to include read-only environment readiness in the final handoff and PR description. Use `--markdown` for a report, `--pr` for a pull-request description template, and `--json` for scripts or automation; JSON includes `checklist[]` labels for the executable handoff next actions. Use `--output` to also write the selected output format to a workspace-contained file. Use `--fail-on-blockers` when a handoff gate should exit non-zero if blockers remain."],
        },
        CommandHelp {
            name: "/test",
            listing: "/test [discover] [--json] [--output path]|run [--json] [--output path] [-- <command>]",
            summary: "Discover or run project tests through deepcli's tool layer.",
            usage: &[
                "/test [discover] [--json] [--output path]",
                "/test run [--json] [--output path]",
                "/test run [--json] [--output path] -- <command>",
            ],
            examples: &[
                "/test discover --json --output .deepcli/exports/tests.json",
                "/test run --json --output .deepcli/exports/test-run.json",
                "/test run --json --output .deepcli/exports/test-run.json -- cargo test",
            ],
            notes: &["Test runs go through the permission policy and are recorded in the active session when available. Put an explicit command after `--` when using `/test run` with `--json` or `--output`. Use `--json` for the stable `deepcli.test.inspect.v1` schema and `--output` to write the selected format to a workspace-contained file."],
        },
        CommandHelp {
            name: "/compiler",
            listing: "/compiler [check|plan|setup|install|test] [--smoke] [--json] [--output path]",
            summary: "Target-first shortcut for compiler Docker/image checks and setup.",
            usage: &[
                "/compiler [--json] [--output path]",
                "/compiler check [--json] [--output path]",
                "/compiler plan [--smoke] [--json] [--output path]",
                "/compiler setup [--smoke] [--json] [--output path]",
                "/compiler install [--smoke] [--json] [--output path]",
                "/compiler test [--json] [--output path]",
            ],
            examples: &[
                "/compiler",
                "/compiler --json",
                "/compiler plan --smoke --json",
                "/compiler setup --smoke",
                "deepcli compiler --json",
            ],
            notes: &["Plain `/compiler` checks the compiler environment; action forms run the matching check, plan, setup, install, or test step for the compiler target. Use `/compiler plan --smoke` for a no-change preview before `/compiler setup`."],
        },
        CommandHelp {
            name: "/install",
            listing: "/install [docker|compiler] [--smoke] [--json] [--output path]",
            summary: "Prepare or install a local docker or compiler environment.",
            usage: &[
                "/install [docker|compiler] [--smoke] [--json] [--output path]",
                "/compiler install [--smoke] [--json] [--output path]",
                "deepcli install docker --smoke",
            ],
            examples: &[
                "/install docker --smoke",
                "deepcli install compiler --smoke",
            ],
            notes: &["`/install` prepares the selected docker or compiler environment; re-run with the same target to update it. Use `/compiler plan --smoke` first when you want a no-change preview."],
        },
        CommandHelp {
            name: "/git",
            listing: "/git status|diff|branch|message [--json] [--output path]|create-branch <name>|commit <message> [--dry-run] [--json]",
            summary: "Run common Git inspection and controlled write operations.",
            usage: &[
                "/git status [--json] [--output path]",
                "/git diff [--staged|--cached] [--json] [--output path]",
                "/git branch [--json] [--output path]",
                "/git message [--json] [--output path]",
                "/git create-branch <name> [--dry-run] [--json] [--output path]",
                "/git commit <message> [--dry-run] [--json] [--output path]",
            ],
            examples: &[
                "/git status --json",
                "/git diff --staged --json",
                "/git status --json --output .deepcli/exports/git-status.json",
                "/git message",
                "/git create-branch feature/my-work --dry-run --json",
                "/git commit checkpoint --dry-run --json",
                "deepcli git status --json",
            ],
            notes: &[
                "Read-only Git commands support the stable `deepcli.git.inspect.v1` JSON schema with executable next actions.",
                "`--output` writes the selected read-only Git output to a workspace-contained file.",
                "Git write dry-runs support the stable `deepcli.git.action.v1` JSON schema and do not execute Git writes.",
                "While an agent is running, read-only `/git status|diff|branch|message` is available, but `--output` and Git write actions must wait or use `/stop` first.",
                "Unknown Git options are rejected instead of being silently ignored.",
                "Branch creation and commits go through the permission policy.",
            ],
        },
        CommandHelp {
            name: "/web",
            listing: "/web search <query>",
            summary: "Run a permission-checked web search through deepcli's network tool.",
            usage: &["/web search <query>", "/web <query>"],
            examples: &["/web search rust ownership"],
            notes: &["Queries that look like secrets are rejected before any network request."],
        },
        CommandHelp {
            name: "/prompt",
            listing: "/prompt list|get <name>|render <name> [--file path] [key=value...] [--json] [--output path]|save <name> <body>|delete <name>",
            summary: "Manage reusable local prompts.",
            usage: &[
                "/prompt list [--json] [--output path]",
                "/prompt get <name> [--json] [--output path]",
                "/prompt render <name> [--file path] [key=value...] [--json] [--output path]",
                "/prompt save <name> <body>",
                "/prompt delete <name>",
            ],
            examples: &[
                "/prompt list --json --output .deepcli/exports/prompts.json",
                "/prompt get code-review --json",
                "/prompt render code-review --file src/lib.rs task='review parser change' --json --output .deepcli/exports/rendered-prompt.json",
                "/prompt save reviewer 'Review the current diff'",
                "/prompt delete reviewer",
            ],
            notes: &["Project prompts can override built-in prompt names until the custom file is deleted.", "`/prompt render` expands {{workspace}}, {{cwd}}, {{branch}}, {{diff}}, {{file}}, {{file_content}}, and custom key=value variables.", "Use `--json` for the stable `deepcli.prompt.inspect.v1` schema on read-only prompt commands and `--output` to write the selected format to a workspace-contained file."],
        },
        CommandHelp {
            name: "/skill",
            listing: "/skill list [--json] [--output path]|generate <name> <description>|run <name> [--json] [--output path]",
            summary: "Discover, generate, and run local deepcli skills.",
            usage: &[
                "/skill list [--json] [--output path]",
                "/skill generate <name> <description>",
                "/skill run <name> [--json] [--output path]",
            ],
            examples: &[
                "/skill list --json --output .deepcli/exports/skills.json",
                "/skill run compiler --json --output .deepcli/exports/compiler-skill.json",
                "/skill generate compiler 'SysY compiler workflow'",
            ],
            notes: &["Skill file, shell, network, and Git operations still go through normal permissions.", "Use `--json` for the stable `deepcli.skill.inspect.v1` schema on read-only skill commands and `--output` to write the selected format to a workspace-contained file."],
        },
        CommandHelp {
            name: "/agent",
            listing: "/agent list [--json] [--output path]|show <id> [--json] [--output path]|spawn <task>",
            summary: "Manage sub-agent task descriptors.",
            usage: &[
                "/agent list [--json] [--output path]",
                "/agent show <id> [--json] [--output path]",
                "/agent spawn <task>",
            ],
            examples: &[
                "/agent list --json --output .deepcli/exports/agents.json",
                "/agent show 6155c14e --json --output .deepcli/exports/agent.json",
                "/agent spawn inspect failing compiler tests",
            ],
            notes: &["Sub-agent depth is bounded by configuration.", "`/agent show` accepts a unique id prefix. Use `--json` for the stable `deepcli.agent.inspect.v1` schema on read-only agent commands and `--output` to write the selected format to a workspace-contained file."],
        },
        CommandHelp {
            name: "/btw",
            listing: "/btw ask <question>|list [--json] [--output path] [session_id|--current] [--all]|answer <id> [--current] [--json] [--output path] <answer>|clear [session_id|--current] [--json] [--output path]",
            summary: "Queue and answer by-the-way questions without interrupting the main task.",
            usage: &[
                "/btw ask <question>",
                "/btw list [--json] [--output path] [session_id|--current] [--all]",
                "/btw answer <id> [--current] [--json] [--output path] <answer>",
                "/btw clear [session_id|--current] [--json] [--output path]",
            ],
            examples: &[
                "/btw ask should I use v4-flash if v4-pro is slow?",
                "/btw list",
                "/btw list --json --output .deepcli/exports/btw.json",
                "/btw answer 1a2b3c4d --json --output .deepcli/exports/btw-answer.json after tests",
            ],
            notes: &["Without an explicit session, list and answer can find the latest matching open question. Use `--json` for the stable `deepcli.btw.list.v1` read schema or `deepcli.btw.action.v1` action schema, and `--output` to write the selected format to a workspace-contained file."],
        },
        CommandHelp {
            name: "/approval",
            listing: "/approval list [--json] [--output path] [session_id|--current] [--all]|approve <id> [--current] [--json] [--output path]|deny <id> [--current] [--json] [--output path]|clear [session_id|--current] [--json] [--output path]",
            summary: "Inspect and resolve pending approval requests.",
            usage: &[
                "/approval list [--json] [--output path] [session_id|--current] [--all]",
                "/approval approve <id> [--current] [--json] [--output path]",
                "/approval deny <id> [--current] [--json] [--output path]",
                "/approval clear [session_id|--current] [--json] [--output path]",
            ],
            examples: &[
                "/approval list",
                "/approval list --json --output .deepcli/exports/approvals.json",
                "/approval approve 1a2b3c4d --json --output .deepcli/exports/approval-approve.json",
            ],
            notes: &["Without an explicit session, list finds the latest matching pending approval request and approve/deny can locate unique ids across recent sessions. Use `--json` for the stable `deepcli.approval.list.v1` read schema or `deepcli.approval.action.v1` action schema, and `--output` to write the selected format to a workspace-contained file."],
        },
        CommandHelp {
            name: "/session",
            listing: "/session list [--all] [--limit n] [--json] [--output path]|search <query> [--limit n] [--json] [--output path]|next [--json] [--output path] [session_id|--current]|diagnose [--limit n] [--json] [--output path] [session_id|--current]|rename <session_id|--current> <title>|prune-empty [--dry-run|--force] [--json] [--output path]|show [--json] [--output path] [session_id|--current]|history [--limit n] [--json] [--output path] [session_id|--current]|summary [--json] [--output path] [session_id|--current]|tools [--failed] [--limit n] [--json] [--output path] [session_id|--current]|tests [--limit n] [--json] [--output path] [session_id|--current]|diffs [--limit n] [--json] [--output path] [session_id|--current]|backups [--limit n] [--json] [--output path] [session_id|--current]|restore-backup <name|latest> [--path <target>] [--session id|--current] [--dry-run] [--json] [--output path]|export [session_id|--current] [path]",
            summary: "Inspect, debug, and export persisted session context.",
            usage: &[
                "/session list [--all] [--limit n] [--json] [--output path]",
                "/session search <query> [--limit n] [--json] [--output path]",
                "/session next [--json] [--output path] [session_id|--current]",
                "/session diagnose [--limit n] [--json] [--output path] [session_id|--current]",
                "/session rename <session_id|--current> <title>",
                "/session prune-empty [--dry-run|--force] [--json] [--output path]",
                "/session show [--json] [--output path] [session_id|--current]",
                "/session history [--limit n] [--json] [--output path] [session_id|--current]",
                "/session summary [--json] [--output path] [session_id|--current]",
                "/session tools [--failed] [--limit n] [--json] [--output path] [session_id|--current]",
                "/session tests [--limit n] [--json] [--output path] [session_id|--current]",
                "/session diffs [--limit n] [--json] [--output path] [session_id|--current]",
                "/session backups [--limit n] [--json] [--output path] [session_id|--current]",
                "/session restore-backup <name|latest> [--path <target>] [--session id|--current] [--dry-run] [--json] [--output path]",
                "/session export [session_id|--current] [path]",
            ],
            examples: &["/session list", "/session list --limit 5", "/session list --json --output .deepcli/exports/sessions.json", "/session search compiler --limit 5", "/session search compiler --json --output .deepcli/exports/session-search.json", "/session next", "/session next --json --output .deepcli/exports/next.json", "/session diagnose --limit 5", "/session diagnose --json --output .deepcli/exports/session-diagnose.json", "/session history --json --output .deepcli/exports/session-history.json", "/session tools --failed --json --output .deepcli/exports/session-tools.json", "/session tests --json", "/session rename a1b2c3d4 compiler lv9 repair", "/session prune-empty --dry-run", "/session prune-empty --json --output .deepcli/exports/prune-empty.json", "/session prune-empty --force", "/session list --all", "/session history --limit 20", "/session tools --failed --limit 5", "/session diffs --limit 5", "/session backups --limit 5", "/session restore-backup latest --path src/lib.rs --dry-run --json", "/session restore-backup latest --dry-run --json --output .deepcli/exports/restore-preview.json", "/session export"],
            notes: &["`/session list` hides empty one-shot sessions by default; use `--all` to include them and `--limit`/`-n` to cap long lists. `/session list` supports `--json`/`--output` through `deepcli.session.list.v1`; `/session search` supports the same through `deepcli.session.search.v1`, so resume pickers and external history UIs do not need to parse text. Search JSON also includes next actions and a matching `checklist[]`: resume preview, history, next, and diagnose for the top hit, or list/resume actions when nothing matches. `/session next` aggregates the likely recovery or continuation actions and supports `--json`/`--output` through the stable `deepcli.next.v1` schema; JSON `nextActions` and `quickLinks` are directly executable `deepcli ...` commands, with `checklist[]` for main actions and `quickLinkChecklist[]` for auxiliary links. `/session diagnose` adds signal counts, latest failures, recent tests, and quick diagnostic commands; use `--json` for the stable `deepcli.session.diagnose.v1` schema, where `recommendedNextActions` and `quickLinks` also use executable `deepcli ...` commands and expose matching checklists, and `--output` to write the selected format to a workspace-contained file. `/session prune-empty` defaults to dry-run and supports `--json`/`--output` through `deepcli.session.prune_empty.v1`, so cleanup previews can be reviewed before `--force`; JSON next actions stay in the JSON workflow with `deepcli session prune-empty --force --json`, list/history follow-ups, and matching `checklist[]`. `/session show|history|summary|tools|tests|diffs|backups` support `--json`/`--output` through the stable `deepcli.session.inspect.v1` schema for external UIs and automation. `/session restore-backup --dry-run --json` emits `deepcli.session.restore_backup.v1` with a redacted diff, target path, selected backup, and next actions; real restore can also use `--json`/`--output` while still writing through the tool executor. While the agent is running, `/session` is limited to read-only inspection and restore-backup dry-run preview without `--output`; rename, export, forced cleanup, real restore, and preview artifact writes must wait or use `/stop`. `/session tools --failed` jumps to the latest failed or denied tool calls. Session ids accept a unique prefix. Without an explicit session, content-specific commands fall back to the latest session that has that content."],
        },
        CommandHelp {
            name: "/cleanup",
            listing: "/cleanup [sessions] [--dry-run|--force] [--json] [--output path]",
            summary: "Shortcut for safely previewing or deleting empty one-shot sessions.",
            usage: &[
                "/cleanup",
                "/cleanup sessions",
                "/cleanup --json",
                "/cleanup --json --output <workspace-relative-path>",
                "/cleanup --force",
                "/session prune-empty [--dry-run|--force] [--json] [--output path]",
            ],
            examples: &[
                "/cleanup",
                "/cleanup --json --output .deepcli/exports/cleanup.json",
                "/cleanup sessions --force",
                "deepcli cleanup sessions --json",
            ],
            notes: &["`/cleanup` maps to `/session prune-empty`, so it defaults to dry-run, skips the current session, skips titled empty sessions, redacts titles, and only deletes candidates when `--force` is passed. Use `--json` for the stable `deepcli.session.prune_empty.v1` schema, whose dry-run next action is `deepcli session prune-empty --force --json` with a matching checklist item."],
        },
        CommandHelp {
            name: "/resume",
            listing: "/resume [session_id|candidates] [--dry-run] [--json] [--output path]",
            summary: "Resume a saved session, or list resumable sessions when no id is provided.",
            usage: &[
                "/resume",
                "/resume <session_id>",
                "/resume <session_id> --dry-run --json",
                "/resume candidates --json [--limit n]",
                "/resume --dry-run --json --output .deepcli/exports/resume.json",
            ],
            examples: &[
                "/resume",
                "/resume 6155c14e-85e5-4600-a081-29359cc232f2",
                "deepcli resume 6155c14e --dry-run --json",
                "deepcli resume candidates --json",
            ],
            notes: &["Session ids accept a unique prefix. In the TUI, `/resume` opens a current-workspace session picker with selected-session activity, summary, and recent-message preview. Without an id, resume candidates skip sessions from other workspace paths, diagnostic-only sessions that only contain tool, test, or audit records, local clarification-only sessions created from low-information input, and brief completed one-turn tasklets; explicit ids can still inspect a specific session. Use `--dry-run` or `--preview` with `--json` for the stable `deepcli.resume.preview.v1` report; it only reads persisted session files, writes optional workspace-contained output, and does not start the TUI, create a session, or call a provider. `candidates --json` emits `deepcli.resume.candidates.v1`, explaining which current-workspace sessions are eligible, which are hidden, and why, so history UIs can distinguish missing history from filtered diagnostic sessions; when no eligible candidate exists, hidden empty sessions add `deepcli session prune-empty --dry-run --json` as the first recovery action, and tool-only or non-resumable sessions add a session diagnose action. Preview, candidates, and error JSON expose executable next actions plus matching `checklist[]` items so recovery UIs can render actions without parsing report text. If no current-workspace resumable session exists, JSON mode keeps the same schema with `status=error`, `selected=null`, an error object, and next actions before returning non-zero."],
        },
        CommandHelp {
            name: "/rename",
            listing: "/rename <title>",
            summary: "Rename the active session title.",
            usage: &["/rename <title>"],
            examples: &["/rename compiler lv9 repair"],
            notes: &[],
        },
        CommandHelp {
            name: "/stop",
            listing: "/stop",
            summary: "Stop the currently running TUI task and keep the session resumable.",
            usage: &["/stop"],
            examples: &["/stop"],
            notes: &["The session is marked paused and can be resumed later."],
        },
        CommandHelp {
            name: "/quit",
            listing: "/quit",
            summary: "Exit the current interactive session.",
            usage: &["/quit"],
            examples: &["/quit"],
            notes: &[],
        },
        CommandHelp {
            name: "/terminal",
            listing: "/terminal [--dry-run|--no-open] [--app name] [--json] [--output path]",
            summary: "Open a terminal in the current workspace directory.",
            usage: &[
                "/terminal",
                "/terminal --app iTerm2",
                "/terminal --dry-run",
                "/terminal --dry-run --json",
                "/terminal --app iTerm2 --dry-run --json",
                "/terminal --dry-run --json --output .deepcli/exports/terminal.json",
            ],
            examples: &[
                "/terminal",
                "/terminal --app iTerm2",
                "/terminal --dry-run --json",
                "deepcli terminal --app iTerm2 --dry-run --json",
                "deepcli terminal --dry-run --json",
            ],
            notes: &["`/terminal` uses the same local `open_terminal` tool as the agent runtime. If `DEEPCLI_TERMINAL_APP` is unset, deepcli infers supported defaults from `TERM_PROGRAM`, so iTerm users get iTerm2 automatically. Set `DEEPCLI_TERMINAL_APP=iTerm2` to change the default macOS terminal app explicitly, or use `--app iTerm2` / `--terminal-app iTerm2` as a one-shot override; the command is shell-quoted as `open -a <app> .`. Use `--dry-run` or `--no-open` to inspect the workspace, app, and command without creating a process. `--json` emits the stable `deepcli.terminal.v1` schema, including `app`, `command`, `workspaceCommand` for manually entering the same workspace, and `--output` writes the selected format to a workspace-contained file."],
        },
    ]
}

fn normalize_help_topic(topic: &str) -> String {
    let trimmed = topic.trim();
    if trimmed.starts_with('/') {
        trimmed.to_string()
    } else {
        format!("/{trimmed}")
    }
}

fn format_help_topic(topic: &CommandHelp) -> String {
    let mut lines = vec![
        format!("{} - {}", topic.name, topic.summary),
        format!(
            "running-safe: {}",
            if is_running_safe_command_name(topic.name) {
                "yes"
            } else {
                "no"
            }
        ),
        "usage:".to_string(),
    ];
    lines.extend(topic.usage.iter().map(|usage| format!("  {usage}")));
    if !topic.examples.is_empty() {
        lines.push("examples:".to_string());
        lines.extend(topic.examples.iter().map(|example| format!("  {example}")));
    }
    if !topic.notes.is_empty() {
        lines.push("notes:".to_string());
        lines.extend(topic.notes.iter().map(|note| format!("  {note}")));
    }
    lines.join("\n")
}
